//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int billingID { get; set; }
        public Nullable<int> guestIDFK { get; set; }
        public int billingExtras { get; set; }
        public int roomCharge { get; set; }
        public bool paid { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
