//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int bookingID { get; set; }
        public int roomIDFK { get; set; }
        public string bookingStart { get; set; }
        public string bookingEnd { get; set; }
        public int numGuests { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
