//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public Guest()
        {
            this.Billings = new HashSet<Billing>();
        }
    
        public string name { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public int bookingIDFK { get; set; }
        public string comment { get; set; }
        public int guestID { get; set; }
        public string checkInDate { get; set; }
        public string checkOutDate { get; set; }
    
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
